version: '3'
services:
  db:
    image: mysql
    container_name: goapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goapi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - goapi-network

  app:
    build: .
    container_name: goapi_app
    volumes:
      - .:/go/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - goapi-network

networks:
  goapi-network:
    driver: bridge